export const allCountriesOf = {
    'europe': [
        { name: 'Andorra', capital: 'Andorra la Vella' },
        { name: 'Switzerland', capital: 'Bern' },
        { name: 'Bosnia and Herzegovina', capital: 'Sarajevo' },
        { name: 'Belgium', capital: 'Brussels' },
        { name: 'Bulgaria', capital: 'Sofia' },
        { name: 'Åland', capital: 'Mariehamn' },
        { name: 'Belarus', capital: 'Minsk' },
        { name: 'Austria', capital: 'Vienna' },
        { name: 'Italy', capital: 'Rome' },
        { name: 'Faroe Islands', capital: 'Tórshavn' },
        { name: 'Iceland', capital: 'Reykjavik' },
        { name: 'United Kingdom', capital: 'London' },
        { name: 'France', capital: 'Paris' },
        { name: 'Jersey', capital: 'Saint Helier' },
        { name: 'Germany', capital: 'Berlin' },
        { name: 'Czech Republic', capital: 'Prague' },
        { name: 'Albania', capital: 'Tirana' },
        { name: 'Cyprus', capital: 'Nicosia' },
        { name: 'Denmark', capital: 'Copenhagen' },
        { name: 'Gibraltar', capital: 'Gibraltar' },
        { name: 'Estonia', capital: 'Tallinn' },
        { name: 'Hungary', capital: 'Budapest' },
        { name: 'Greece', capital: 'Athens' },
        { name: 'Spain', capital: 'Madrid' },
        { name: 'Guernsey', capital: 'St. Peter Port' },
        { name: 'Ireland', capital: 'Dublin' },
        { name: 'Finland', capital: 'Helsinki' },
        { name: 'Croatia', capital: 'Zagreb' },
        { name: 'Isle of Man', capital: 'Douglas' },
        { name: 'Monaco', capital: 'Monaco' },
        { name: 'Liechtenstein', capital: 'Vaduz' },
        { name: 'Montenegro', capital: 'Podgorica' },
        { name: 'Moldova', capital: 'Chișinău' },
        { name: 'Luxembourg', capital: 'Luxembourg' },
        { name: 'Lithuania', capital: 'Vilnius' },
        { name: 'Latvia', capital: 'Riga' },
        { name: 'Malta', capital: 'Valletta' },
        { name: 'North Macedonia', capital: 'Skopje' },
        { name: 'Netherlands', capital: 'Amsterdam' },
        { name: 'Portugal', capital: 'Lisbon' },
        { name: 'Poland', capital: 'Warsaw' },
        { name: 'Sweden', capital: 'Stockholm' },
        { name: 'Slovenia', capital: 'Ljubljana' },
        { name: 'Norway', capital: 'Oslo' },
        { name: 'Romania', capital: 'Bucharest' },
        { name: 'Russia', capital: 'Moscow' },
        { name: 'Serbia', capital: 'Belgrade' },
        { name: 'San Marino', capital: 'City of San Marino' },
        { name: 'Ukraine', capital: 'Kyiv' },
        { name: 'Slovakia', capital: 'Bratislava' },
        { name: 'Svalbard and Jan Mayen', capital: 'Longyearbyen' },
        { name: 'Vatican City', capital: 'Vatican City' },
        { name: 'Kosovo', capital: 'Pristina' }
    ],
    'asia': [
        { name: 'Bahrain', capital: 'Manama' },
        { name: 'Armenia', capital: 'Yerevan' },
        { name: 'United Arab Emirates', capital: 'Abu Dhabi' },
        { name: 'Brunei', capital: 'Bandar Seri Begawan' },
        { name: 'Bhutan', capital: 'Thimphu' },
        { name: 'Afghanistan', capital: 'Kabul' },
        { name: 'Azerbaijan', capital: 'Baku' },
        { name: 'Hong Kong', capital: 'City of Victoria' },
        { name: 'China', capital: 'Beijing' },
        { name: 'Iran', capital: 'Tehran' },
        { name: 'India', capital: 'New Delhi' },
        { name: 'Christmas Island', capital: 'Flying Fish Cove' },
        { name: 'Cocos [Keeling] Islands', capital: 'West Island' },
        { name: 'Bangladesh', capital: 'Dhaka' },
        { name: 'Jordan', capital: 'Amman' },
        { name: 'Indonesia', capital: 'Jakarta' },
        { name: 'Georgia', capital: 'Tbilisi' },
        { name: 'Israel', capital: 'Jerusalem' },
        { name: 'British Indian Ocean Territory', capital: 'Diego Garcia' },
        { name: 'Iraq', capital: 'Baghdad' },
        { name: 'North Korea', capital: 'Pyongyang' },
        { name: 'Cambodia', capital: 'Phnom Penh' },
        { name: 'Sri Lanka', capital: 'Colombo' },
        { name: 'Japan', capital: 'Tokyo' },
        { name: 'South Korea', capital: 'Seoul' },
        { name: 'Kazakhstan', capital: 'Astana' },
        { name: 'Laos', capital: 'Vientiane' },
        { name: 'Kyrgyzstan', capital: 'Bishkek' },
        { name: 'Kuwait', capital: 'Kuwait City' },
        { name: 'Lebanon', capital: 'Beirut' },
        { name: 'Maldives', capital: 'Malé' },
        { name: 'Nepal', capital: 'Kathmandu' },
        { name: 'Mongolia', capital: 'Ulan Bator' },
        { name: 'Macao', capital: 'Macao' },
        { name: 'Palestine', capital: 'Ramallah' },
        { name: 'Saudi Arabia', capital: 'Riyadh' },
        { name: 'Oman', capital: 'Muscat' },
        { name: 'Qatar', capital: 'Doha' },
        { name: 'Myanmar [Burma]', capital: 'Naypyidaw' },
        { name: 'Thailand', capital: 'Bangkok' },
        { name: 'Singapore', capital: 'Singapore' },
        { name: 'Malaysia', capital: 'Kuala Lumpur' },
        { name: 'Philippines', capital: 'Manila' },
        { name: 'Pakistan', capital: 'Islamabad' },
        { name: 'Turkmenistan', capital: 'Ashgabat' },
        { name: 'Syria', capital: 'Damascus' },
        { name: 'Vietnam', capital: 'Hanoi' },
        { name: 'Uzbekistan', capital: 'Tashkent' },
        { name: 'Tajikistan', capital: 'Dushanbe' },
        { name: 'Turkey', capital: 'Ankara' },
        { name: 'Yemen', capital: "Sana'a" },
        { name: 'Taiwan', capital: 'Taipei' }
    ],
    'america': [
        { name: 'Aruba', capital: 'Oranjestad' },
        { name: 'Belize', capital: 'Belmopan' },
        { name: 'Anguilla', capital: 'The Valley' },
        { name: 'Barbados', capital: 'Bridgetown' },
        { name: 'Grenada', capital: "St. George's" },
        { name: 'Greenland', capital: 'Nuuk' },
        { name: 'Saint Barthélemy', capital: 'Gustavia' },
        { name: 'Antigua and Barbuda', capital: "Saint John's" },
        { name: 'Honduras', capital: 'Tegucigalpa' },
        { name: 'Canada', capital: 'Ottawa' },
        { name: 'Bahamas', capital: 'Nassau' },
        { name: 'Dominica', capital: 'Roseau' },
        { name: 'Costa Rica', capital: 'San José' },
        { name: 'Jamaica', capital: 'Kingston' },
        { name: 'Guatemala', capital: 'Guatemala City' },
        { name: 'Curacao', capital: 'Willemstad' },
        { name: 'Cuba', capital: 'Havana' },
        { name: 'Bonaire', capital: 'Kralendijk' },
        { name: 'Haiti', capital: 'Port-au-Prince' },
        { name: 'Dominican Republic', capital: 'Santo Domingo' },
        { name: 'Bermuda', capital: 'Hamilton' },
        { name: 'Guadeloupe', capital: 'Basse-Terre' },
        { name: 'Cayman Islands', capital: 'George Town' },
        { name: 'Saint Kitts and Nevis', capital: 'Basseterre' },
        { name: 'Saint Martin', capital: 'Marigot' },
        { name: 'Saint Lucia', capital: 'Castries' },
        { name: 'Mexico', capital: 'Mexico City' },
        { name: 'Puerto Rico', capital: 'San Juan' },
        { name: 'Martinique', capital: 'Fort-de-France' },
        { name: 'Saint Pierre and Miquelon', capital: 'Saint-Pierre' },
        { name: 'Panama', capital: 'Panama City' },
        { name: 'Montserrat', capital: 'Plymouth' },
        { name: 'Sint Maarten', capital: 'Philipsburg' },
        { name: 'United States', capital: 'Washington D.C.' },
        { name: 'Nicaragua', capital: 'Managua' },
        { name: 'El Salvador', capital: 'San Salvador' },
        { name: 'Turks and Caicos Islands', capital: 'Cockburn Town' },
        { name: 'Trinidad and Tobago', capital: 'Port of Spain' },
        { name: 'U.S. Virgin Islands', capital: 'Charlotte Amalie' },
        { name: 'Saint Vincent and the Grenadines', capital: 'Kingstown' },
        { name: 'British Virgin Islands', capital: 'Road Town' },
        { name: 'Bolivia', capital: 'Sucre' },
        { name: 'Colombia', capital: 'Bogotá' },
        { name: 'Chile', capital: 'Santiago' },
        { name: 'French Guiana', capital: 'Cayenne' },
        { name: 'Argentina', capital: 'Buenos Aires' },
        { name: 'Brazil', capital: 'Brasília' },
        { name: 'Guyana', capital: 'Georgetown' },
        { name: 'Falkland Islands', capital: 'Stanley' },
        { name: 'Ecuador', capital: 'Quito' },
        { name: 'Peru', capital: 'Lima' },
        { name: 'Paraguay', capital: 'Asunción' },
        { name: 'Venezuela', capital: 'Caracas' },
        { name: 'Suriname', capital: 'Paramaribo' },
        { name: 'Uruguay', capital: 'Montevideo' }
    ],
    'africa': [
        { name: 'Burundi', capital: 'Bujumbura' },
        { name: 'Democratic Republic of the Congo', capital: 'Kinshasa' },
        { name: 'Benin', capital: 'Porto-Novo' },
        { name: 'Angola', capital: 'Luanda' },
        { name: 'Gambia', capital: 'Banjul' },
        { name: 'Republic of the Congo', capital: 'Brazzaville' },
        { name: 'Cape Verde', capital: 'Praia' },
        { name: 'Botswana', capital: 'Gaborone' },
        { name: 'Central African Republic', capital: 'Bangui' },
        { name: 'Cameroon', capital: 'Yaoundé' },
        { name: 'Ivory Coast', capital: 'Yamoussoukro' },
        { name: 'Egypt', capital: 'Cairo' },
        { name: 'Guinea-Bissau', capital: 'Bissau' },
        { name: 'Algeria', capital: 'Algiers' },
        { name: 'Western Sahara', capital: 'El Aaiún' },
        { name: 'Guinea', capital: 'Conakry' },
        { name: 'Djibouti', capital: 'Djibouti' },
        { name: 'Burkina Faso', capital: 'Ouagadougou' },
        { name: 'Eritrea', capital: 'Asmara' },
        { name: 'Ethiopia', capital: 'Addis Ababa' },
        { name: 'Ghana', capital: 'Accra' },
        { name: 'Equatorial Guinea', capital: 'Malabo' },
        { name: 'Gabon', capital: 'Libreville' },
        { name: 'Liberia', capital: 'Monrovia' },
        { name: 'Kenya', capital: 'Nairobi' },
        { name: 'Madagascar', capital: 'Antananarivo' },
        { name: 'Lesotho', capital: 'Maseru' },
        { name: 'Comoros', capital: 'Moroni' },
        { name: 'Libya', capital: 'Tripoli' },
        { name: 'Morocco', capital: 'Rabat' },
        { name: 'Mozambique', capital: 'Maputo' },
        { name: 'Mali', capital: 'Bamako' },
        { name: 'Somalia', capital: 'Mogadishu' },
        { name: 'Namibia', capital: 'Windhoek' },
        { name: 'Nigeria', capital: 'Abuja' },
        { name: 'Malawi', capital: 'Lilongwe' },
        { name: 'Seychelles', capital: 'Victoria' },
        { name: 'South Africa', capital: 'Pretoria' },
        { name: 'Mauritius', capital: 'Port Louis' },
        { name: 'Mauritania', capital: 'Nouakchott' },
        { name: 'Sudan', capital: 'Khartoum' },
        { name: 'Niger', capital: 'Niamey' },
        { name: 'Rwanda', capital: 'Kigali' },
        { name: 'São Tomé and Príncipe', capital: 'São Tomé' },
        { name: 'Saint Helena', capital: 'Jamestown' },
        { name: 'Tanzania', capital: 'Dodoma' },
        { name: 'Sierra Leone', capital: 'Freetown' },
        { name: 'Zimbabwe', capital: 'Harare' },
        { name: 'Togo', capital: 'Lomé' },
        { name: 'Senegal', capital: 'Dakar' },
        { name: 'Réunion', capital: 'Saint-Denis' },
        { name: 'South Sudan', capital: 'Juba' },
        { name: 'Swaziland', capital: 'Lobamba' },
        { name: 'Chad', capital: "N'Djamena" },
        { name: 'Uganda', capital: 'Kampala' },
        { name: 'Mayotte', capital: 'Mamoudzou' },
        { name: 'Tunisia', capital: 'Tunis' },
        { name: 'Zambia', capital: 'Lusaka' }
    ],
    'oceania': [
        { name: 'American Samoa', capital: 'Pago Pago' },
        { name: 'Cook Islands', capital: 'Avarua' },
        { name: 'Australia', capital: 'Canberra' },
        { name: 'Guam', capital: 'Hagåtña' },
        { name: 'Micronesia', capital: 'Palikir' },
        { name: 'Fiji', capital: 'Suva' },
        { name: 'Kiribati', capital: 'South Tarawa' },
        { name: 'Norfolk Island', capital: 'Kingston' },
        { name: 'New Caledonia', capital: 'Nouméa' },
        { name: 'French Polynesia', capital: 'Papeetē' },
        { name: 'New Zealand', capital: 'Wellington' },
        { name: 'Marshall Islands', capital: 'Majuro' },
        { name: 'Northern Mariana Islands', capital: 'Saipan' },
        { name: 'Nauru', capital: 'Yaren' },
        { name: 'Solomon Islands', capital: 'Honiara' },
        { name: 'Palau', capital: 'Ngerulmud' },
        { name: 'Tokelau', capital: 'Fakaofo' },
        { name: 'Tuvalu', capital: 'Funafuti' },
        { name: 'Niue', capital: 'Alofi' },
        { name: 'East Timor', capital: 'Dili' },
        { name: 'Tonga', capital: "Nuku'alofa" },
        { name: 'Papua New Guinea', capital: 'Port Moresby' },
        { name: 'Pitcairn Islands', capital: 'Adamstown' },
        { name: 'Vanuatu', capital: 'Port Vila' },
        { name: 'Samoa', capital: 'Apia' },
        { name: 'Wallis and Futuna', capital: 'Mata-Utu' }
    ]
}